services:
  # Compile container for Composer + NPM + build
  compile:
    image: composer:2
    working_dir: /var/www/html
    volumes:
      - ../../:/var/www/html
    command: >
      sh -c "apk add --no-cache nodejs npm git bash &&
             composer install &&
             npm install &&
             npm run build"

  # Laravel PHP-FPM container
  app:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ../../:/var/www/html
    depends_on:
      - db

  # Nginx container to serve Laravel
  web:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ../../:/var/www/html
    depends_on:
      - app

  # MySQL database
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
